[package]
name = "macros"
version = "0.3.0"
edition = "2024"

[dependencies]
wasm-bindgen = { version = "0.2.111", optional = true }

[features]
use-browser-console = ["wasm-bindgen"]

[dependencies.web-sys]
version = "=0.3.88"
features = [
  "console",
]
